# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Manual Deployment

on:
 workflow_dispatch:
   inputs:
     environment:
       description: 'Environment to run against'
       type: environment
       required: true
 
 
jobs:
 Mule:
   uses: Reema954/SharedWorkFlows/.github/workflows/maven_environment.yml@main
   with:
      environment: ${{inputs.environment}}
      application-name: GithubActions-MavenConfig
      region: ${{vars.REGION}}
   secrets: inherit
